   sres@cnMonoFillPattern    = False            ; want multiple patterns                                                               
;    sres@cnFillPatterns       = (/-1,17/)     ; the patterns                                                                        
;    sres@cnMonoFillScale      = False            ; want different densities                                                            
;    sres@cnFillScales         = (/1,1/)    ; change densities                                                                        
;    sres@cnMonoFillColor      =True                                                                                                     
;    sres@cnFillDotSizeF       = 0.0050