; These files are loaded by default in NCL V6.2.0 or newer
; load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl"
; load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_csm.ncl"
; load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/contributed.ncl"
;
; This file still has to be loaded manually
; load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/shea_util.ncl"
; load "~/shea_util.ncl"
; load "~/shade_coi_alone.ncl"
;*****************************************************
begin
  print("R U OK?")
end